function plotMultipleIsoresponseLMplaneEllipseThresholds()

    linearityString = '';  %either '' or 'nonLinear' (has to be added manually in filename);

    useMetaContrast = true;

    %useConeContrast = true;
    %mRGCOutputSignalType = 'mRGCs'; %'cones' %'mRGCs';

    useConeContrast = true;
    mRGCOutputSignalType = 'cones'; %'cones' %'mRGCs';


    noiseType = 'Gaussian_rceTemplateDistance';
    if (~useConeContrast && strcmp(mRGCOutputSignalType,'cones'))
        noiseType = 'Poisson_rcePoisson';
    end


    matlabDir = strrep(isetbioRootPath, '/toolboxes/isetbio', '');
    rootDir = fullfile(matlabDir, 'toolboxes/ISETBioCSFGenerator/local/t_isoresponseLMplaneEllipses/results');

    if (useConeContrast)
       resultsFileBaseDir = fullfile(rootDir, ...
            sprintf('t_isoresponseLMplaneEllipses_Meta_%d_ConeContrast_1_FEMs_0_mRGCMosaic_%s_%s', useMetaContrast,noiseType, mRGCOutputSignalType));
    else
        resultsFileBaseDir = fullfile(rootDir, ...
            sprintf('t_isoresponseLMplaneEllipses_Meta_%d_ConeContrast_0_FEMs_0_mRGCMosaic_%s_%s', useMetaContrast,noiseType, mRGCOutputSignalType));
    end



    figureFileBaseDir = strrep(resultsFileBaseDir, 'results', 'figures');


    Pts_coneContrast = [
   -0.3000   -0.3000         0; ...
   -0.1500   -0.1500    0.0000; ...
    0.0000    0.0000         0; ...
    0.1500    0.1500         0; ...
    0.3000    0.3000         0; ...
   -0.0500    0.0500         0; ...
    0.0500   -0.0500    0.0000];



    dir(resultsFileBaseDir)
    
    examinedSpatialFrequencyCPD = 0;
    opticsType = 'loadComputeReadyRGCMosaic';
    mosaicEccDegs = [0 0.0];
    mosaicSizeDegs = [1 1];
    orientationDegs = 90;
    
    presentationMode = 'static';

    initializeFig = true;

    theThresholdAxes = []; 
    maxVisualizedThreshold = 0.35;

    for iC = 1:size(Pts_coneContrast,1)
        referenceLMSconeContrast = Pts_coneContrast(iC,:);
        referenceLMSconeContrast(3) = 0;
        if (isempty(linearityString)) && (strcmp(mRGCOutputSignalType, 'mRGCs'))
            thresholdsDataFileName = ...
                sprintf('%sCSF_SF_%2.2fCPD_Optics_%s_EccDegs_x%2.1f_%2.1f_SizeDegs_%2.1fx%2.1f_OriDegs_%2.0f_RefLMScontrast_%2.1f_%2.1f_%2.1f%sLinear.mat', ...
                mRGCOutputSignalType, ...
                examinedSpatialFrequencyCPD, ...
                opticsType, ...
                mosaicEccDegs(1), mosaicEccDegs(2), ...
                mosaicSizeDegs(1),mosaicSizeDegs(2), ...
                orientationDegs, ...
                referenceLMSconeContrast(1)*100, ...
                referenceLMSconeContrast(2)*100, ...
                referenceLMSconeContrast(3)*100, ...
                presentationMode);
        else
            thresholdsDataFileName = ...
                sprintf('%sCSF_SF_%2.2fCPD_Optics_%s_EccDegs_x%2.1f_%2.1f_SizeDegs_%2.1fx%2.1f_OriDegs_%2.0f_RefLMScontrast_%2.1f_%2.1f_%2.1f%s.mat', ...
                mRGCOutputSignalType, ...
                examinedSpatialFrequencyCPD, ...
                opticsType, ...
                mosaicEccDegs(1), mosaicEccDegs(2), ...
                mosaicSizeDegs(1),mosaicSizeDegs(2), ...
                orientationDegs, ...
                referenceLMSconeContrast(1)*100, ...
                referenceLMSconeContrast(2)*100, ...
                referenceLMSconeContrast(3)*100, ...
                presentationMode);
        end

    load(fullfile(resultsFileBaseDir,thresholdsDataFileName), ...
        'options', ...
        'theLMSconeContrastDirections', 'theDeltaLMSconeContrastDirections', ...
        'stimulusRMSLMconeContrast', 'examinedDirectionsOnLMplane', 'thresholdContrasts');

    skippedDirections = 0;
    gratingSceneParams = struct( ...
            'meanLuminanceCdPerM2', options.meanLuminanceCdPerM2, ...
            'meanChromaticityXY', options.meanChromaticityXY, ...
            'backgroundLMSconeExcitations', options.backgroundLMSconeExcitations, ...
            'spectralSupport', 400:20:750, ...
            'fovDegs', options.stimSizeDegs, ...
            'pixelsNum', options.pixelsNum, ...
            'spatialEnvelope', 'rect', ...
            'spatialEnvelopeRadiusDegs', options.stimSizeDegs, ...
            'orientation', options.orientationDegs, ...
            'presentationMode', 'flashed', ... 
            'duration', options.frameDurationSeconds, ...
            'frameDurationSeconds', options.frameDurationSeconds, ...
            'spatialPhase', options.spatialPhaseDegs);

    % Figure for plotting the thresholds on the LM plane
    % along with the stimuli
    hFigStimuliAndThresholds = figure(2346); clf;
    set(hFigStimuliAndThresholds, 'Color', [1 1 1], 'Position', [10 10 1200 1200]);
    set(hFigStimuliAndThresholds, 'HandleVisibility', 'off');
    
    exportFig = true;
    
    

    figName = sprintf('refC_%2.1f_%2.1f_%2.1f%s', 100*referenceLMSconeContrast(1), 100*referenceLMSconeContrast(2), 100*referenceLMSconeContrast(3), linearityString);

    [thresholdDeltaConeContrasts(iC,:,:), theThresholdAxes] = visualizeIsoThresholdEllipsesOnLMplane(...
            theLMSconeContrastDirections, ...
            theDeltaLMSconeContrastDirections, ...
            stimulusRMSLMconeContrast, ...
            examinedSpatialFrequencyCPD, ...
            gratingSceneParams, ...
            examinedDirectionsOnLMplane, ...
            skippedDirections, ...
            thresholdContrasts, ...
            maxVisualizedThreshold, ...
            referenceLMSconeContrast(1:2), ...
            figureFileBaseDir, hFigStimuliAndThresholds, ...
            exportFig, initializeFig, theThresholdAxes, figName);

    initializeFig = false;


    LconeContrastThresholds = squeeze(thresholdDeltaConeContrasts(iC,1,:));
    MconeContrastThresholds = squeeze(thresholdDeltaConeContrasts(iC,2,:));

    [LconeContrastThresholds(:) MconeContrastThresholds(:)]
    save(sprintf('%s_%s%s.mat', mRGCOutputSignalType,noiseType, figName), 'referenceLMSconeContrast', 'LconeContrastThresholds', 'MconeContrastThresholds');

    end


    figName = sprintf('Summary%s%s',mRGCOutputSignalType, linearityString);
    set(hFigStimuliAndThresholds, 'HandleVisibility', 'on');

    if ((~isempty(figureFileBaseDir)) && (exportFig))
        NicePlot.exportFigToPNG(fullfile(figureFileBaseDir,figName), hFigStimuliAndThresholds, 300);
    end

end
