function plotMultipleIsoresponseLMplaneEllipseThresholds()

    linearityString = ''; %'_nonLinear20'
    mRGCOutputSignalType = 'mRGCs'; %'cones' %'mRGCs';
    rootDir = '/Volumes/SSD1M2/Documents/MATLAB/toolboxes/ISETBioCSFGenerator/local/t_isoresponseLMplaneEllipses/results/';
    resultsFileBaseDir = fullfile(rootDir, ...
        sprintf('t_isoresponseLMplaneEllipses_Meta_1_ConeContrast_1_FEMs_0_mRGCMosaic_Gaussian_rceTemplateDistance_%s', mRGCOutputSignalType));
    figureFileBaseDir = strrep(resultsFileBaseDir, 'results', 'figures');


    Pts_coneContrast = [
    0.2384    0.3549   -0.0000; ...
   -0.3058   -0.2796    0.0000; ...
    0.0000    0.0000         0; ...
    0.3058    0.2796   -0.0000; ...
   -0.2384   -0.3549    0.0000];


    dir(resultsFileBaseDir)
    
    examinedSpatialFrequencyCPD = 0;
    opticsType = 'loadComputeReadyRGCMosaic';
    mosaicEccDegs = [0 0.0];
    mosaicSizeDegs = [1 1];
    orientationDegs = 90;
    
    presentationMode = 'static';

    initializeFig = true;

    theThresholdAxes = []; 
    maxVisualizedThreshold = 0.5;

    for iC = 1:size(Pts_coneContrast,1)
        referenceLMSconeContrast = Pts_coneContrast(iC,:);
        referenceLMSconeContrast(3) = 0;
    thresholdsDataFileName = ...
        sprintf('%sCSF_SF_%2.2fCPD_Optics_%s_EccDegs_x%2.1f_%2.1f_SizeDegs_%2.1fx%2.1f_OriDegs_%2.0f_RefLMScontrast_%2.1f_%2.1f_%2.1f%s%s.mat', ...
        mRGCOutputSignalType, ...
        examinedSpatialFrequencyCPD, ...
        opticsType, ...
        mosaicEccDegs(1), mosaicEccDegs(2), ...
        mosaicSizeDegs(1),mosaicSizeDegs(2), ...
        orientationDegs, ...
        referenceLMSconeContrast(1)*100, ...
        referenceLMSconeContrast(2)*100, ...
        referenceLMSconeContrast(3)*100, ...
        presentationMode, linearityString);

    load(fullfile(resultsFileBaseDir,thresholdsDataFileName), ...
        'options', 'stimulusRMSLMconeContrast', 'examinedDirectionsOnLMplane', 'thresholdContrasts');

    skippedDirections = 0;
    gratingSceneParams = struct( ...
            'meanLuminanceCdPerM2', options.meanLuminanceCdPerM2, ...
            'meanChromaticityXY', options.meanChromaticityXY, ...
            'backgroundLMSconeExcitations', options.backgroundLMSconeExcitations, ...
            'spectralSupport', 400:20:750, ...
            'fovDegs', options.stimSizeDegs, ...
            'pixelsNum', options.pixelsNum, ...
            'spatialEnvelope', 'rect', ...
            'spatialEnvelopeRadiusDegs', options.stimSizeDegs, ...
            'orientation', options.orientationDegs, ...
            'presentationMode', 'flashed', ... 
            'duration', options.frameDurationSeconds, ...
            'frameDurationSeconds', options.frameDurationSeconds, ...
            'spatialPhase', options.spatialPhaseDegs);

    % Figure for plotting the thresholds on the LM plane
    % along with the stimuli
    hFigStimuliAndThresholds = figure(2346); clf;
    set(hFigStimuliAndThresholds, 'Color', [1 1 1], 'Position', [10 10 1200 1200]);
    set(hFigStimuliAndThresholds, 'HandleVisibility', 'off');
    
    exportFig = true;
    
    


    figName = sprintf('refC_%2.1f_%2.1f_%2.1f%s', 100*referenceLMSconeContrast(1), 100*referenceLMSconeContrast(2), 100*referenceLMSconeContrast(3), linearityString);
    theThresholdAxes = visualizeIsoThresholdEllipsesOnLMplane(...
            stimulusRMSLMconeContrast, ...
            examinedSpatialFrequencyCPD, gratingSceneParams, ...
            examinedDirectionsOnLMplane, skippedDirections, ...
            thresholdContrasts.*stimulusRMSLMconeContrast, maxVisualizedThreshold, referenceLMSconeContrast(1:2), ...
            figureFileBaseDir, hFigStimuliAndThresholds, ...
            exportFig, initializeFig, theThresholdAxes, figName);

    initializeFig = false;
    end

    figName = sprintf('Summary%s%s',mRGCOutputSignalType, linearityString);
    set(hFigStimuliAndThresholds, 'HandleVisibility', 'on');

    if ((~isempty(figureFileBaseDir)) && (exportFig))
        NicePlot.exportFigToPNG(fullfile(figureFileBaseDir,figName), hFigStimuliAndThresholds, 300);
    end

end
