function t_isoresponseLMplaneEllipses_mRGCpaperApplications(options)
%
% These are t_isoresponseLMplaneEllipses runs used in the 2025 mRGC model paper

% UTTBSkip

% Examples:
%{

    % ETTBSkip

coneValidationThresholdsEcc0degs = [...
 0.0114
    0.0116
    0.0128
    0.0145
    0.0150
    0.0153
    0.0130
    0.0116
    0.0106
    0.0113
    0.0135
    0.0149
    0.0151
    0.0152
    0.0131
    0.0115
];


t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [0.59 0.59], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc0degs);





mRGCValidationThresholdsEcc0degs = [...
  0.0236
    0.0333
    0.0514
    0.0380
    0.0234
    0.0210
    0.0182
    0.0184
    0.0231
    0.0319
    0.0510
    0.0362
    0.0239
    0.0192
    0.0174
    0.0182
];


% 4628 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [0.59 0.59], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...        
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc0degs);




mRGCValidationThresholdsEcc4degs = [...
0.0269
    0.0318
    0.0387
    0.0366
    0.0296
    0.0237
    0.0232
    0.0235
    0.0272
    0.0336
    0.0418
    0.0385
    0.0301
    0.0250
    0.0208
    0.0214
];

% 4633 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-4 0], ...
        'mRGCMosaicRawSizeDegs', [3 3], ...
        'mosaicEccDegs', [-4.0 0], ...
        'mosaicSizeDegs', [2.1 2.1], ...
        'stimSizeDegs', 2.5, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc4degs);

coneValidationThresholdsEcc4degs = [
0.0093
    0.0090
    0.0098
    0.0116
    0.0117
    0.0111
    0.0099
    0.0093
    0.0080
    0.0084
    0.0103
    0.0117
    0.0111
    0.0110
    0.0103
    0.0088
];

t_isoresponseLMplaneEllipses(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-4 0], ...
        'mRGCMosaicRawSizeDegs', [3 3], ...
        'mosaicEccDegs', [-4.0 0], ...
        'mosaicSizeDegs', [2.1 2.1], ...
        'stimSizeDegs', 2.5, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc4degs);

mRGCValidationThresholdsEcc7degs = [...
0.0264
    0.0321
    0.0382
    0.0361
    0.0320
    0.0283
    0.0251
    0.0249
    0.0286
    0.0315
    0.0348
    0.0389
    0.0328
    0.0267
    0.0265
    0.0262
];



%4680 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-7 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-7.0 0], ...
        'mosaicSizeDegs', [3.2 3.2], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc7degs);


coneValidationThresholdsEcc7degs = [...
 0.0070
    0.0075
    0.0081
    0.0092
    0.0092
    0.0092
    0.0085
    0.0075
    0.0070
    0.0073
    0.0083
    0.0095
    0.0103
    0.0097
    0.0086
    0.0075
];



%4680 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-7 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-7.0 0], ...
        'mosaicSizeDegs', [3.2 3.2], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc7degs);

coneValidationThresholdsEcc10degs = [...
0.0092
    0.0093
    0.0106
    0.0116
    0.0130
    0.0109
    0.0103
    0.0086
    0.0086
    0.0092
    0.0101
    0.0121
    0.0120
    0.0115
    0.0100
    0.0091
];


%2155 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-10 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-10.0 0], ...
        'mosaicSizeDegs', [2.9 2.9], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc10degs);


mRGCvalidationThresholdsEcc10degs = [...
0.0070
    0.0077
    0.0080
    0.0092
    0.0097
    0.0090
    0.0079
    0.0069
    0.0069
    0.0071
    0.0082
    0.0099
    0.0100
    0.0092
    0.0079
    0.0068
];

t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-10 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-10.0 0], ...
        'mosaicSizeDegs', [2.9 2.9], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCvalidationThresholdsEcc10degs);

coneValidationThresholdsEcc14degs = [...
0.0070
    0.0077
    0.0080
    0.0092
    0.0097
    0.0090
    0.0079
    0.0069
    0.0069
    0.0071
    0.0082
    0.0099
    0.0100
    0.0092
    0.0079
    0.0068
];

% 2195 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-14 0], ...
        'mRGCMosaicRawSizeDegs', [5 5], ...
        'mosaicEccDegs', [-14 0], ...
        'mosaicSizeDegs', [4.1 4.1], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc14degs);

mRGCvalidationThresholdsEcc14degs = [...
0.0504
    0.0486
    0.0513
    0.0607
    0.0787
    0.0839
    0.0692
    0.0586
    0.0492
    0.0512
    0.0523
    0.0604
    0.0782
    0.0829
    0.0704
    0.0582
];

% 2195 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-14 0], ...
        'mRGCMosaicRawSizeDegs', [5 5], ...
        'mosaicEccDegs', [-14 0], ...
        'mosaicSizeDegs', [4.1 4.1], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCvalidationThresholdsEcc14degs);


mRGCValidationThresholdsEcc19degs = [...
0.0608
    0.0594
    0.0611
    0.0766
    0.1069
    0.1183
    0.1032
    0.0720
    0.0620
    0.0615
    0.0629
    0.0770
    0.1055
    0.1208
    0.0973
    0.0715
];

% 2146 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-19 0], ...
        'mRGCMosaicRawSizeDegs', [6 6], ...
        'mosaicEccDegs', [-19 0], ...
        'mosaicSizeDegs', [6 6], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc19degs);


coneValidationThresholdsEcc19degs = [... 
0.0056
    0.0060
    0.0068
    0.0078
    0.0079
    0.0074
    0.0066
    0.0059
    0.0058
    0.0059
    0.0071
    0.0073
    0.0076
    0.0076
    0.0067
    0.0061
];


% 2146 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-19 0], ...
        'mRGCMosaicRawSizeDegs', [6 6], ...
        'mosaicEccDegs', [-19 0], ...
        'mosaicSizeDegs', [6 6], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc19degs);

mRGCValidationThresholdsEcc25degs = [...
0.0875
    0.0747
    0.0880
    0.1068
    0.1446
    0.2064
    0.1657
    0.1077
    0.0888
    0.0814
    0.0839
    0.1054
    0.1413
    0.2111
    0.1631
    0.1100
];

% 1069 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-25 0], ...
        'mRGCMosaicRawSizeDegs', [7 7], ...
        'mosaicEccDegs', [-25 0], ...
        'mosaicSizeDegs', [5.8 5.8], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc25degs);


coneValidationThresholdsEcc25degs = [...
0.0061
    0.0065
    0.0068
    0.0077
    0.0093
    0.0079
    0.0067
    0.0061
    0.0060
    0.0064
    0.0068
    0.0078
    0.0084
    0.0081
    0.0072
    0.0065
];


% 1069 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-25 0], ...
        'mRGCMosaicRawSizeDegs', [7 7], ...
        'mosaicEccDegs', [-25 0], ...
        'mosaicSizeDegs', [5.8 5.8], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc25degs);

coneValidationThresholdsEcc32degs = [... 
0.0057
    0.0052
    0.0058
    0.0063
    0.0059
    0.0061
    0.0063
    0.0056
    0.0052
    0.0055
    0.0056
    0.0054
    0.0063
    0.0062
    0.0063
    0.0059
];

% 1090 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-32 0], ...
        'mRGCMosaicRawSizeDegs', [9 9], ...
        'mosaicEccDegs', [-32 0], ...
        'mosaicSizeDegs', [9 9], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', coneValidationThresholdsEcc32degs);

mRGCValidationThresholdsEcc32degs = [...
 0.1181
    0.0962
    0.0953
    0.1096
    0.1374
    0.1885
    0.1893
    0.1399
    0.1107
    0.1061
    0.0975
    0.1112
    0.1371
    0.1817
    0.2020
    0.1437
];

% 1090 mRGCs
t_isoresponseLMplaneEllipses(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...      % Select between {'cones', 'mRGCs'}
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'employMosaicSpecificConeFundamentals', true, ...
        'mRGCMosaicRawEccDegs', [-32 0], ...
        'mRGCMosaicRawSizeDegs', [9 9], ...
        'mosaicEccDegs', [-32 0], ...
        'mosaicSizeDegs', [9 9], ...
        'stimSizeDegs', 6.2, ...
        'pixelsNum', 512, ...
        'spatialFrequency', 0.0, ...         
        'spatialPhaseDegs', 0.0, ...
        'presentationMode', 'counterphasemodulated', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'examinedDirectionsOnLMplane', 0:22.5:(360-22.5), ...
        'validationThresholds', mRGCValidationThresholdsEcc32degs);


% Run with mRGCMosaic (linear response)
     t_isoresponseLMplaneEllipses(...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ... 
        'whichNoisyInstanceNre', 'Gaussian', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true);

% Run with mRGCMosaic (ON mRGC mosaic, non-linear activation function, simulating case in a high saturation regime)
     t_isoresponseLMplaneEllipses(...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'simulateHighSaturationRegime', true, ...
        'simulateONOFFmosaic', false, ...
        'mRGCOutputSignalType', 'mRGCs', ...  
        'whichNoisyInstanceNre', 'Gaussian', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true);

% Run with mRGCMosaic (ON mRGC mosaic, half-wave recrifier activation function, simulating case in subthreshold regime)
t_isoresponseLMplaneEllipses(...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'simulateHalfWaveRectification', true, ...
        'simulateONOFFmosaic', false, ...
        'mRGCOutputSignalType', 'mRGCs', ...  
        'whichNoisyInstanceNre', 'Gaussian', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true);

%}

