% t_spatialCSF_mRGCExamples
%
% These are examples for t_spatialCSF that exercise the mRGC calculations.

% Examples:
%{
    % mRGCMosaic nre basic test
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'validationThresholds', [0.0067    0.0050    0.0056    0.0120], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2);

    % mRGCMosaic nre basic test with fixational eye movements
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.01, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', true, ...
        'temporalFilterValues', [0.0118    0.0076    0.0106    0.0185], ...
        'oiPadMethod', 'zero', ...
        'validationThresholds', [], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2); 

    % mRGCMosaic nre, but pick off cone excitations as output
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachResponse', false, ...
        'maxVisualizedNoisyResponseInstances', 9, ... 
        'validationThresholds', [ 0.1443    0.1547    0.2420    0.5703]);
%}
