% t_spatialCSF_mRGCExamples
%
% These are examples for t_spatialCSF that exercise the mRGC calculations.

% Examples:
%{
    % mRGCMosaic nre basic test: achromatic CSF
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'spatialFreqs', [0.3 0.6 1.2 3 6 12 30 60], ...
        'nTest', 1024, ...
        'validationThresholds', [0.5112 0.2519 0.1664 0.1859 0.1833 0.1797 0.5479 1.0000]);





    % mRGCMosaic nre test: L-M,  native optics, drifting CSF @ fovea
    validationThresholds = [...
    0.0128
    0.0126
    0.0127
    0.0129
    0.0126
    0.0126
    0.0132
    0.0135
    0.0133
    0.0143
    0.0154
    0.0182
    0.0229
    0.0292
    0.0341
    0.0447
    0.0729
    0.3493
    1.0000
    1.0000
];
    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


    % mRGCMosaic nre test: achromatic  native optics, drifting CSF @ fovea
    validationThresholds = [...
    0.0464
    0.0481
    0.0458
    0.0439
    0.0453
    0.0457
    0.0425
    0.0440
    0.0409
    0.0386
    0.0330
    0.0317
    0.0323
    0.0365
    0.0482
    0.0693
    0.1401
    0.3646
    1.0000
    1.0000
];

    t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


    % mRGCMosaic input cone mosaic nre test: achromatic  native optics, drifting CSF @ fovea
    validationThresholds = [...
0.0107
    0.0096
    0.0103
    0.0094
    0.0102
    0.0099
    0.0104
    0.0111
    0.0099
    0.0109
    0.0128
    0.0142
    0.0180
    0.0227
    0.0293
    0.0500
    0.1087
    0.2658
    1.0000
    1.0000
];

    t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


    % mRGCMosaic nre test: 
    % achromatic  AO optics, drifting CSF @ fovea (1x1 degs)
    validationThresholds = [...
0.0464
    0.0481
    0.0458
    0.0439
    0.0448
    0.0451
    0.0417
    0.0428
    0.0387
    0.0359
    0.0285
    0.0246
    0.0219
    0.0196
    0.0202
    0.0200
    0.0229
    0.0332
    0.0596
    0.2036

    ];

    t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);

validationThresholds = [...

];

 t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-2 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [-2.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);

validationThresholds = [...

];
t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputvSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [-2 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [-2.0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);

validationThresholds = [...

];

t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0 0], ...
        'mosaicSizeDegs', [1 1], ...
        'stimSizeDegs', 1.2, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);



%}
