% t_spatialCSF_EMExamples
%
% Temporal filter examples for t_spatialCSF

% Examples:
%{
    % Validate with cone contrast, temporal filter, meta contrast.  This
    % is a delta function and should not change threshold relative to the
    % same parameters without a filter.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 4, ...
        'temporalFilterValues', [1 0 0 0], ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0208    0.0370    0.0770    0.3300]);

    % Validate with temporal filter based on photocurrent, meta contrast.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 12, ...
        'frameDurationSeconds', 0.025, ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0194    0.0358    0.0785    0.2899]);

    % Validate with temporal filter based Watson's filter with
    % its default parameters.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 12, ...
        'frameDurationSeconds', 0.025, ...
        'temporalFilterValues', 'watsonFilter', ...
        'visualizeEachScene', true, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);
%}