% Compute spatial CSF in the achromatic direction in the presence of fEM
%
% Description:
%    Use ISETBioCSFGenerator to run out CSFs in the achromatic color direction
%    in the presence of fixatinal eye movements using the cone photocurrent
%    signal, and 2Hz drifting gratings.
%    This example uses the new @cMosaic object, an SVM computational observer,
%    operating on the output of a quadrature energy spatial pooling mechanism
%    and square windowed gratings of constant size.
%
% See also: t_thresholdEngine, t_modulatedGratingsSceneGeneration,
%           t_chromaticThresholdContour, computeThresholdTAFC, computePerformanceTAFC
%

% History:
%   8/24/21  NPC   Wrote it
%   7/28/26  NPC   Modernized it


%
% Example with Gaussian noise added on the noise-free photocurrent responses
%

% If ('zeroPistonAndTiltZernikeCoefficients', true) is passed to 
% t_spactialCSF(), use the validationThresholdsForZ1Z2Z3setTo0 thresholds
validationThresholds = [0.0108    0.0203    0.0613    0.2277];
%    validationThresholdsForZ1Z2Z3setTo0 = [0.0112    0.0198    0.0526    0.2223];

t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1.3, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds', validationThresholds);

%
% Example with Photocurrent noise added on the noise-free photocurrent responses
%

validationThresholds = [0.0265    0.0513    0.1384    0.4771];
t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Photocurrent', ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds', validationThresholds);
