% t_spatialCSF_mRGCExamples
%
% These are examples for t_spatialCSF that exercise the mRGC calculations.

% Examples:
%{
    % mRGCMosaic nre basic test: achromatic CSF
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'spatialFreqs', [0.3 0.6 1.2 3 6 12 30 60], ...
        'nTest', 1024, ...
        'validationThresholds', [0.5112 0.2519 0.1664 0.1859 0.1833 0.1797 0.5479 1.0000]);





    % mRGCMosaic CSF: L-M,  native optics @ fovea (2x2degs)
    
    validationThresholds = [...

];
    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'validationThresholds', validationThresholds);


t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'validationThresholds', validationThresholds);

    % mRGCMosaic CSF: L+M+S,  native optics @ fovea (2x2degs)

    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


    % input cone Mosaic CSF: L-M,  native optics @ fovea (2x2degs)
    validationThresholds = [
0.0056
    0.0053
    0.0051
    0.0055
    0.0056
    0.0056
    0.0056
    0.0057
    0.0057
    0.0066
    0.0069
    0.0080
    0.0096
    0.0128
    0.0144
    0.0188
    0.0367
    0.1854
    0.9750
    1.0000
];

    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds)

% input cone Mosaic CSF: L+M+S,  native optics @ fovea (2x2degs)
    validationThresholds = [
0.0062
    0.0066
    0.0063
    0.0063
    0.0062
    0.0067
    0.0061
    0.0071
    0.0070
    0.0070
    0.0081
    0.0086
    0.0111
    0.0152
    0.0208
    0.0325
    0.0640
    0.1925
    1.0000
    1.0000
];

    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds)

 

 
    % mRGCMosaic nre test: 
    % achromatic  AO optics, drifting CSF @ fovea (1x1 degs)
    validationThresholds = [...
 0.0279
    0.0302
    0.0287
    0.0286
    0.0310
    0.0296
    0.0285
    0.0269
    0.0261
    0.0232
    0.0199
    0.0177
    0.0148
    0.0129
    0.0136
    0.0152
    0.0188
    0.0228
    0.0538
    0.1683
    ];

    t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0.0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


validationThresholds = [...
0.0089
    0.0089
    0.0086
    0.0087
    0.0088
    0.0086
    0.0085
    0.0090
    0.0091
    0.0091
    0.0089
    0.0094
    0.0101
    0.0097
    0.0111
    0.0125
    0.0158
    0.0244
    0.0529
    0.1904
];

t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'adaptiveOptics6MM', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0 0], ...
        'mosaicSizeDegs', [2 2], ...
        'stimSizeDegs', 2.3, ...
        'pixelsNum', 512, ...
        'stimulusChroma', 'red-green', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', validationThresholds);


% DIFFERENT ECCENTRICITIES

mRGCvalidationThresholds_0degs = [...
   0.0591
    0.0628
    0.0631
    0.0652
    0.0596
    0.0632
    0.0630
    0.0573
    0.0591
    0.0555
    0.0511
    0.0501
    0.0472
    0.0539
    0.0695
    0.1023
    0.2005
    0.5066
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0 0], ...
        'mosaicSizeDegs', [0.59 0.59], ...
        'stimSizeDegs', 1, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', mRGCvalidationThresholds_0degs);



coneValidationThresholds_0degs = [...
0.0160
    0.0160
    0.0156
    0.0160
    0.0154
    0.0154
    0.0155
    0.0158
    0.0164
    0.0172
    0.0195
    0.0229
    0.0263
    0.0326
    0.0474
    0.0737
    0.1536
    0.3821
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [0 0], ...
        'mRGCMosaicRawSizeDegs', [2 2], ...
        'mosaicEccDegs', [0 0], ...
        'mosaicSizeDegs', [0.59 0.59], ...
        'stimSizeDegs', 1, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', coneValidationThresholds_0degs);

% 4 degs

mRGCvalidationThresholds_4degs = [...
0.0478
    0.0488
    0.0469
    0.0467
    0.0434
    0.0427
    0.0407
    0.0368
    0.0349
    0.0343
    0.0406
    0.0558
    0.0811
    0.1764
    0.4451
    1.0000
    1.0000
    1.0000
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-4 0], ...
        'mRGCMosaicRawSizeDegs', [3 3], ...
        'mosaicEccDegs', [-4.0 0], ...
        'mosaicSizeDegs', [2.1 2.1], ...
        'stimSizeDegs', 2.5, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', mRGCvalidationThresholds_4degs);



coneValidationThresholds_4degs = [...
0.0120
    0.0119
    0.0112
    0.0117
    0.0123
    0.0123
    0.0119
    0.0128
    0.0136
    0.0164
    0.0196
    0.0282
    0.0433
    0.0929
    0.2071
    0.5167
    1.0000
    1.0000
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-4 0], ...
        'mRGCMosaicRawSizeDegs', [3 3], ...
        'mosaicEccDegs', [-4.0 0], ...
        'mosaicSizeDegs', [2.1 2.1], ...
        'stimSizeDegs', 2.5, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.2), log10(120), 20), ...
        'validationThresholds', coneValidationThresholds_4degs);



% 7 degs

mRGCvalidationThresholds_7degs = [...
0.0450
    0.0435
    0.0455
    0.0419
    0.0460
    0.0421
    0.0422
    0.0393
    0.0398
    0.0354
    0.0312
    0.0327
    0.0345
    0.0492
    0.1038
    0.2863
    1.0000
    1.0000
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', '3/4', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'mRGCs', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-7 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-7.0 0], ...
        'mosaicSizeDegs', [3.2 3.2], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.05), log10(60), 20), ...
        'validationThresholds', mRGCvalidationThresholds_7degs);



coneValidationThresholds_7degs = [...
0.0093
    0.0092
    0.0089
    0.0100
    0.0096
    0.0101
    0.0100
    0.0117
    0.0127
    0.0142
    0.0212
    0.0330
    0.0598
    0.1470
    0.3777
    0.6694
    1.0000
    1.0000
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-7 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-7.0 0], ...
        'mosaicSizeDegs', [3.2 3.2], ...
        'stimSizeDegs', 4.2, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.05), log10(60), 20), ...
        'validationThresholds', coneValidationThresholds_7degs);

coneValidationThresholds_10degs = [...
0.0093
    0.0092
    0.0089
    0.0100
    0.0096
    0.0101
    0.0100
    0.0117
    0.0127
    0.0142
    0.0212
    0.0330
    0.0598
    0.1470
    0.3777
    0.6694
    1.0000
    1.0000
    1.0000
    1.0000
];

t_spatialCSF(...
        'parPoolSize', 'extreme', ...
        'useMetaContrast', true, ...
        'whichNoiseFreeNre', 'mRGCMosaic', ...
        'mRGCOutputSignalType', 'cones', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', ~true, ...
        'responseVisualizationFunction', @nreVisualizeMRGCmosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli', 2, ...
        'opticsType', 'loadComputeReadyRGCMosaic', ...
        'mRGCMosaicRawEccDegs', [-10 0], ...
        'mRGCMosaicRawSizeDegs', [4 4], ...
        'mosaicEccDegs', [-10.0 0], ...
        'mosaicSizeDegs', [4 4], ...
        'stimSizeDegs', 5.2, ...
        'pixelsNum', 512, ...
        'employMosaicSpecificConeFundamentals', true, ...
        'stimulusChroma', 'luminance', ...
        'orientationDegs', 120, ...
        'presentationMode', 'drifted', ...
        'stimDurationTemporalCycles', 1.0, ...
        'frameDurationSeconds', (1/2.5)/8, ...
        'temporalFrequencyHz', 2.5, ...
        'nTest', 1024, ...
        'psychometricCurveSamplesNum', 5, ...
        'spatialFreqs', logspace(log10(0.05), log10(60), 20), ...
        'validationThresholds', coneValidationThresholds_10degs);



%}
