% t_spatialCSF_TemporalFilterExamples
%
% Temporal filter examples for t_spatialCSF

% Examples:
%{
    % Validate with cone contrast, temporal filter, meta contrast.  This
    % is a delta function and should not change threshold relative to the
    % same parameters without a filter.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 4, ...
        'temporalFilterValues', [1 0 0 0], ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0208    0.0370    0.0770    0.3300]);

    % SHOULD UPDATE THE FOLLOWING TO USE CONTRAST, BUT NEED TO FUSS WITH
    % SIGMA TO GET THRESHOLDS IN RANGE AND THEN UPDATE VALIDATION DATA
    % Validate with temporal filter based on photocurrent, meta contrast.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1.3, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0088    0.0152    0.0374    0.1279]);

    % Validate with temporal filter based on photocurrent, meta contrast.
    % This version with eye movements.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1.3, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0108    0.0203    0.0613    0.2277]);

    % Validate with temporal filter based Watson's filter with
    % its default parameters.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 10, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast',false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'watsonFilter', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0471    0.0903    0.1963    0.7077]);

    % Validate with temporal filter based Watson's filter with
    % its default parameters and eye movements
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 10, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast',false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', 'watsonFilter', ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0485    0.0838    0.2022    0.7811]);

    % For comparison to the above. Same conditions with no temporal filter,
    % no FEMs.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast',false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', [], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0040    0.0061    0.0151    0.0646]);

    % For comparison to the above. Same conditions with no temporal filter,
    % with FEMS
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 1, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast',false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 2, ...
        'spatialFreqs', [4 8 16 32], ...
        'temporalFilterValues', [], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0040    0.0073    0.0173    0.0624]);
%}