% t_spatialCSF_EMExamples
%
% Eye movement examples using cMosaic, for t_spatialCSF

% Examples:
%{
    % Verify that cMosaic FEMs work without crashing. Same EM paths on
    % train and test.
    t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'testEMsMatchTrain', true, ...
        'nTrainEMs', 4, ...
        'nTestEMs', 4, ...
        'nTrain', 1, ...
        'nTest', 32', ...
        'stimSizeDegs', 1, ...
        'pixelsNum', 256, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'validationThresholds', [0.0183    0.0403    0.0838    0.4432], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli',2);

    % Verify that cMosaic FEMs work without crashing. Different EM paths on
    % train and test. Performance should be very bad, which it is.
    %
    % Can't use meta contrast for this case.
    t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'testEMsMatchTrain', false, ...
        'nTrainEMs', 4, ...
        'nTestEMs', 4, ...
        'nTrain', 1, ...
        'nTest', 32', ...
        'stimSizeDegs', 1, ...
        'pixelsNum', 256, ...
        'temporalFilterValues', [], ...
        'oiPadMethod', 'zero', ...
        'validationThresholds', [1.0000    1.0000    1.0000    1.0000], ...
        'visualizeEachScene', false, ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'maxVisualizedNoisyResponseInstances', 2, ...
        'maxVisualizedNoisyResponseInstanceStimuli',2);
%}