% t_spatialCSF_EMExamples
%
% Temporal filter examples for t_spatialCSF

% Examples:
%{
    % Validate with cone contrast, temporal filter, meta contrast.  This
    % is a delta function and should not change threshold relative to the
    % same parameters without a filter.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', false, ...
        'numberOfFrames', 4, ...
        'temporalFilterValues', [1 0 0 0], ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  [0.0208    0.0370    0.0770    0.3300]);

   % Validate with cone contrast, temporal filter based on photocurrent, meta contrast.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 4, ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);

   % Validate with cone contrast, temporal filter based Watson's filter with
   % its default parameters.
    t_spatialCSF('useMetaContrast', true, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Poisson', ...
        'whichClassifierEngine', 'rcePoisson', ...
        'useConeContrast', false, ...
        'useFixationalEMs', true, ...
        'numberOfFrames', 4, ...
        'temporalFilterValues', 'watsonFilter', ...
        'visualizeEachResponse', false, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);
%}